Support different scheduler addresses for nested clients inside worker (#238)
* Support different scheduler addresses for nested clients inside worker

Signed-off-by: eric <eric117649@gmail.com>

* Handle case when disconnecting a client that wasn't fully initialized

fixes:
Exception ignored in: <function Client.__del__ at 0x7fc96914c220>
Traceback (most recent call last):
  File "/workspaces/scaler/scaler/client/client.py", line 144, in __del__
    self.disconnect()
  File "/workspaces/scaler/scaler/client/client.py", line 385, in disconnect
    if self._stop_event.is_set():
       ^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_stop_event'

when running:
python -m unittest tests.test_client.TestClient.test_client_no_address_outside_worker

Signed-off-by: eric <eric117649@gmail.com>

* Simplify scheduler address resolution logic

Since scheduler address is a required attribute of Processor
It will never be None if we are able to get the current processor

Signed-off-by: eric <eric117649@gmail.com>

* Update docs

Signed-off-by: eric <eric117649@gmail.com>

* Bump version

Signed-off-by: eric <eric117649@gmail.com>

---------

Signed-off-by: eric <eric117649@gmail.com>
Co-authored-by: sharpener6 <1sc2l4qi@duck.com>